package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/kkrypt0nn/argane/internal/policies"
	"github.com/kkrypt0nn/argane/internal/rule"
)

const rulesOutDir = "./www/src/content/docs/rules"
const rulesMarkdownTemplate = `---
title: %s
description: %s
---

%s

###### Auto generated by scripts/gendoc on %s
`

func generatePolicyDocs() error {
	policies := [][]rule.Rule{
		policies.BaselinePolicy(nil),
		policies.RestrictedPolicy(nil),
	}

	for _, policyRules := range policies {
		for _, r := range policyRules {
			if err := generateRuleDoc(r); err != nil {
				return err
			}
		}
	}

	fmt.Println("Rules documentation files have been successfully generated")
	return nil
}

func generateRuleDoc(r rule.Rule) error {
	id := r.ID()
	filename := strings.ReplaceAll(id, ":", "_") + ".md"
	markdownDescription := r.MarkdownDescription()
	shortDescription := strings.SplitN(markdownDescription, "\n\n", 2)[0]
	content := fmt.Sprintf(rulesMarkdownTemplate, id, shortDescription, markdownDescription, time.Now().Format("2-Jan-2006"))
	return os.WriteFile(filepath.Join(rulesOutDir, filename), []byte(content), 0644)
}
